blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/teamreboott/data-modori/discussions
    about: Ask general usage questions and discuss with other Data-Modori community members
  - name: ğŸŒ Explore OpenMMLab
    url: https://reboott.ai/
    about: Get know more about Teamreboott